### ISSUE TITLE
How do load avsi scripts?

### ISSUE THREAD

**Issue by ArtexJay** [Anime4000/IFME#222]
I noticed that on the official website there is support for AviSynth and support for plugins for it like mfToon or linedarker but I cannot figure out how to add them to IFME. 
I tried to follow the guide for installing/using AviSynth+

**Comment by Anime4000** [comment]
just drag avs script into, later FFmpeg will detect

**Comment by ArtexJay** [comment]
> just drag avs script into, later FFmpeg will detect

Doesn't seem to work for me and when i try using the "+" button it gives me the following error, for reference I am trying to add mFToon-v0.54.avsi I also get an Unhandled exception when trying to add the avs script from your guide when testing if AviSynth+ is working with IFME:
![image](https://user-images.githubusercontent.com/32932497/199111703-1cfcb1b6-6656-4266-809a-375f6f189f07.png)


"See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at IFME.FFmpeg.MediaInfo..ctor(String filePath, String frameRate) in D:\Users\Anime4000\Documents\GitHub\IFME\IFME.FFmpeg\MediaInfo.cs:line 40
   at IFME.frmMain.MediaFileListAdd(String path, Boolean isImages, String frameRate) in D:\Users\Anime4000\Documents\GitHub\IFME\IFME\frmMain.Function.cs:line 183
   at IFME.frmMain.tsmiImportFiles_Click(Object sender, EventArgs e) in D:\Users\Anime4000\Documents\GitHub\IFME\IFME\frmMain.cs:line 2063
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9105.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
IFME
    Assembly Version: 8.0.2.0
    Win32 Version: 8.0.2
    CodeBase: file:///C:/Users/TheEm/Downloads/IFME-8.0_beta2-debug/IFME.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9105.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.1
    CodeBase: file:///C:/Users/TheEm/Downloads/IFME-8.0_beta2-debug/Newtonsoft.Json.DLL
----------------------------------------
IFME.OSManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0
    CodeBase: file:///C:/Users/TheEm/Downloads/IFME-8.0_beta2-debug/IFME.OSManager.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
IFME.FFmpeg
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0
    CodeBase: file:///C:/Users/TheEm/Downloads/IFME-8.0_beta2-debug/IFME.FFmpeg.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9105.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


"

**Comment by Anime4000** [comment]
for `*.avsi` you need copy that AviSynth Autoload into this folder `C:\Program Files (x86)\AviSynth+\plugins64+`

or

using `Import()`, example:
```
Import("C:\path\to\get\mFToon-v0.54.avsi")
DirectShowSource(Video).ConvertToYV12()
...
```

can test if `avs` script works via AvsPmod: https://avspmod.github.io/

**Comment by ArtexJay** [comment]
> opy that AviSynth Autoload into this folder `C:\Program Files (x86)\AviSynth+\plugins64+`
> 
> or

avspmod gives me a series of errors while when it loads to run. And i seem to have directshow "cannot open *.mp4 file error". 

for the `*.avsi` file i moved it to `C:\Program Files (x86)\AviSynth+\plugins64+` 

I still cannot get `*.avs` files to be imported into IFME to check if AviSynth+ is working with IFME either. I'm trying beta3 debug if that matters.

**Comment by Anime4000** [comment]
nice, most everything Avisynth plugin and script must put at `C:\Program Files (x86)\AviSynth+\plugins64+`

so far IFME only accept 64-bit for now, I still working to work legacy AviSynth in 32-bit
