### ISSUE TITLE
frame black band problem

### ISSUE THREAD

**Issue by Shiniori-raws** [Anime4000/IFME#225]
Hello, I have a request from you. I want a setting that will remove the black bands around the edges when adjusting the film. Can you help?

For example, I want to remove the black bands at the top and bottom of the image.

https://img.imgyukle.com/2023/11/25/y5apnh.png

While using xvid4psp, I had this setting and could easily remove the tapes. Your program is very good, but this is the only setting missing.

**Comment by Anime4000** [comment]
maybe you can enter FFmpeg `-vf`` at Advanced Decoder Option

**Comment by Anime4000** [comment]
![image](https://github.com/Anime4000/IFME/assets/1908715/042a55f8-d776-4dec-a96e-7a5a4c24af77)
![image](https://github.com/Anime4000/IFME/assets/1908715/7e71cb6a-dcc4-4b52-8e24-1bbceb696471)

for now use this: `crop=1280:720:0:0` (width : height : x : y)

get beta10 here: https://sourceforge.net/projects/ifme/files/encoder-gui/8.0/

**Comment by Shiniori-raws** [comment]
Can you please add the crop event to beta 11, I'm looking forward to it.

**Comment by Shiniori-raws** [comment]
Could you please add x265 NVENC 10 and 12 bit settings.

By the way, Ryzen 9 7950x processor system. I have avx2 but I get 17 fps at most. But if you add nvenc, I will get even higher.

**Comment by Shiniori-raws** [comment]
http://msystem.waw.pl/x265/  The group confused me a lot, I don't know which one to download and where to put it.

**Comment by Anime4000** [comment]
> http://msystem.waw.pl/x265/ The group confused me a lot, I don't know which one to download and where to put it.

You can download highest version and replace based on bitdepth
![image](https://github.com/Anime4000/IFME/assets/1908715/215b24fa-a009-4b80-84e4-f3d4ebfd26a5)

**Comment by Anime4000** [comment]
I can add 10 bit NVEnc, but cannot 12 bit, my GPU can't support it, also Rigaya NVEnc only include 10 bit.
![Internet Friendly Media Encoder 8 0 beta 11 ( 'Celestial Cascade' ) 2](https://github.com/Anime4000/IFME/assets/1908715/edaa03a6-03e0-4563-823b-67061ff0b0bf)

about cropping, I haven't completed the GUI, for now you need use Advanced Decoder Command-Line

**Comment by Shiniori-raws** [comment]
> about cropping, I haven't completed the GUI, for now you need use Advanced Decoder Command-Line

Can you upload it specifically for me so I can use it? I will download it again when the new version is released. please

**Comment by Anime4000** [comment]
when use `crop=1280:720:0:0` make sure Resolution is set to `auto`...

for level, add `--level 5.2` via **Encoder CLI** button

I have release beta 11 here
https://sourceforge.net/projects/ifme/files/encoder-gui/8.0/

**Comment by Shiniori-raws** [comment]
![A Model Family S01E01 Episode 1 2160p NF WEB-DL DDP5 1 Atmos H 265-APEX mp4_001710964](https://github.com/Anime4000/IFME/assets/144055706/fb0ecb16-368d-48b1-8f2f-df60af628212)

1280x720 resolution black cerveve codes top 92 bottom 92

The encode result will be 1280x536 resolution. I am adding the code you gave, but it keeps giving errors and does not translate.

-vf
crop=1280:720:0:0 92:92:x:y

-vf
crop=1280:536:0:0 

-vf
crop=1280:536:92:92

-vf
crop=1280:720:92:92    

I tried these and it gave an error.

  I'm about to go crazy 

please help me

**Comment by Shiniori-raws** [comment]
![Ekran görüntüsü 2023-12-09 001457](https://github.com/Anime4000/IFME/assets/144055706/352d151d-be5b-40fd-b976-78f5fafc9584)

Beto 10 is fine, beta 11 is problematic, only x265 Ryuga works, others do not work.

**Comment by Shiniori-raws** [comment]
![Ekran görüntüsü 2023-12-09 010152](https://github.com/Anime4000/IFME/assets/144055706/2002f7db-001f-4b9e-95d9-9682271e1341)


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Erişim engellendi
   at System.Diagnostics.Process.Kill()
   at IFME.OSManager.ProcessEx.Terminate(Int32 ParentPID) in D:\Users\Anime4000\Documents\GitHub\IFME\IFME.OSManager\ProcessEx.cs:line 38
   at IFME.ProcessManager.Stop() in D:\Users\Anime4000\Documents\GitHub\IFME\IFME\ProcessManager.cs:line 119
   at IFME.frmMain.btnStop_Click(Object sender, EventArgs e) in D:\Users\Anime4000\Documents\GitHub\IFME\IFME\frmMain.cs:line 306
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
IFME
    Assembly Version: 8.0.10.0
    Win32 Version: 8.0.10
    CodeBase: file:///C:/IFME-8.0_beta10-debug/IFME.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.1
    CodeBase: file:///C:/IFME-8.0_beta10-debug/Newtonsoft.Json.DLL
----------------------------------------
IFME.OSManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0
    CodeBase: file:///C:/IFME-8.0_beta10-debug/IFME.OSManager.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9191.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
IFME.FFmpeg
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0
    CodeBase: file:///C:/IFME-8.0_beta10-debug/IFME.FFmpeg.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Anime4000** [comment]
I have replied to your discord
